on: 
  pull_request:
  workflow_dispatch:

env:
  cache-date: "2023-10-04"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: node_modules
          key: ${{ env.cache-date }}-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles("package-lock.json") }}
          restore-keys: ${{ env.cache-date }}-${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install Dependencies
        if: steps.cache_dependencies.outputs.cache-hit != "true"
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
